### ISSUE TITLE
Create 2D Array to store individual 'grid square' info

### ISSUE THREAD

**Issue by EricESeitz** [CompSciLauren/minesweeper#21]
The 2D array will mirror what the user will interact with. Each 'grid square' corresponding to one assigned 2D array space.

Some new object will store necessary values that can be called upon.
I'm thinking when the user clicks on a grid square, a broad function like 'clickRun(int, int) is executed. both ints will be the location of the grid (i.e (3,4) is right 3 down 4)

this broad function (clickRun) will take the given coordinates and 'ping' the 2D array for status. So a function like 'isNextToMine' will return the number of mines the square is neighbor to (0, 1, 2, 3, etc...)
Others could be boolean, like 'isMine', either true or false. 

Once it gets these basic properties from the 2D array, other functions would use these to display mine numbers, fail game or reveal empty squares etc.

This might be a bit broad for one Issue, but I also wanted to get everyone's feedback on whether my thinking is correct or not

**Comment by CompSciLauren** [comment]
Hmm I think that all sounds about right.

> this broad function (clickRun) will take the given coordinates and 'ping' the 2D array for status. So a function like 'isNextToMine' will return the number of mines the square is neighbor to (0, 1, 2, 3, etc...)
Others could be boolean, like 'isMine', either true or false.

I'm unsure how this is going to work exactly, I would need to look into it more to understand better, but I think this is the right idea.

This sounds like a lot to do. Definitely don't need to do the displaying of the information yet, that could be in a future Issue. Not sure how you'd break down the rest of that into smaller Issues. I guess just try to do the minimum amount to make it work? And we can build out the rest in future Issues? But this is pretty vague lol, does that make sense though?

**Comment by EricESeitz** [comment]
> This sounds like a lot to do.

You aren't kidding, and I'd like to note that this is NOT set in stone, this is just my first crack at getting things working!

I'll definitely have to do some code-drawing next time we meet, I think if we can nail down a code map it'll clear up a lot of confusion and give us a solid plan to work with.

I'll try to explain it a bit more, maybe this will help. This is just a version 1 of a thought map I'm mulling over.

Inside the index.htm there will be the broad 'clickFunction' that is executed upon a square click.

clickFunction will call on functions in a seperate .js file (main.js for the time being) that will contain the code for the 2D array and functions that communicate with the 2D array
Example: isMine(arr[x][y]) will go to the 2D array 'arr' at coordinates (x, y) and return some variable stored there (i.e minePlaced = true/false)

inside clickFunction, the output of these 'array communicator' functions are what we'll use to determine win/loss, what numbers to put on the squares if any, etc.

The array will be initialized inside of the index.htm after we get the user defined array size.

Does this help any? I could also be poorly explaining it...

**Comment by CompSciLauren** [comment]
Yeah that makes sense! Like you said though, it'd probably be easier to understand if we could sit down and write out the basic logic/steps. What you're saying makes sense to me, it could work I think!

**Comment by EricESeitz** [comment]
Ok, it isn't much but I have a small testing example of an n-dimensional array working. It's on a new branch called 'MultiArray' (should have been a branch off of my own, not master. Whoops). I'll have to work on storing info and calling functions later, but so far I think we have a 2D array function that we can work with. Let me know if you have any thoughts on it

**Comment by CompSciLauren** [comment]
Hahaha "BOOM!" I think it looks really good so far. Only thing I want to point out is that we probably want to use 'const' and 'let' instead of 'var'. I don't expect anyone to have seen this yet but I started a [best practices page](https://github.com/CompSciLauren/minesweeper/wiki/Best-Practices) and it mentions that near the bottom. However, I failed to explain why I believe this. [This page](https://evertpot.com/javascript-let-const/) explains it nicely at the top of the page. Can you let me know if this sounds good or else what your opinion is on this?

I finished my Issue. I'm not sure how we will combine these things or what yet, but can you take a look at mine too? It prompts the user for input and creates the grid based on their input, and each square has a unique identifier which will come into play with your 2D array I imagine (though still working all this out in my head lol).

**Comment by CompSciLauren** [comment]
Resolved by #24, closing
