### ISSUE TITLE
Add function to generate bombs in random locations

### ISSUE THREAD

**Issue by CompSciLauren** [CompSciLauren/minesweeper#22]
## Things to Do for this Issue

- Create a function to randomly assign some squares to have bombs.
- Add logic for what happens when user clicks a square
    - If it is a bomb: All bomb-squares turn a solid-filled black color (revealing all hidden bombs to user).
    - If it is not a bomb: Change that square's color to be light gray.
- Game should no longer be playable. The game over screen can be a JavaScript alert that says the game is over. After user clicks okay, page should automatically refresh so it once again asks for a grid size input, as it currently does when the page is first loaded.

Note: Remember that the game over screen can always be modified later to be a nice design once we have reached the Minimal Viable Product milestone.
Note: User gets to input number of mines in each game.

Requirements from Canvas:
- Number mines (from user)
   - Min: 1
    - Max: number of squares - 1
- Randomly place the mines

**Comment by EricESeitz** [comment]
I can start on randomly assigning mines

**Comment by CompSciLauren** [comment]
Resolved by #32, closing
