### ISSUE TITLE
Create readme structure & fill out details

### ISSUE THREAD

**Issue by CompSciLauren** [CompSciLauren/minesweeper#3]
Things to include:
- Project description
- How to play game _(do we need this? should we include a link to a classic Minesweeper game to show what the game looked like originally?)_
- How to get started using this project as a developer
- Link to Best Practices page on Wiki
- Cite sources

**Comment by EricESeitz** [comment]
First thought says we should include some basic instructions in the Readme, and maybe also inside the index.htm (i.e 'Right click to plant flag, Left Click to dig space' or something to that effect)

Also, should we note any meetings we'll have as a group? Challenges or things of note that will come up? This might be more class-orientated than strictly for the game but they might be important to have included.
